# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cfg-analysis',
                'doc_host': 'https://Matthew-Berthoud.github.io',
                'git_url': 'https://github.com/Matthew-Berthoud/cfg-analysis',
                'lib_path': 'cfg_analysis'},
  'syms': {'cfg_analysis.core': {'cfg_analysis.core.foo': ('core.html#foo', 'cfg_analysis/core.py')}}}
